### ISSUE TITLE
making a new issue co z i dont want jostro to die 

### ISSUE THREAD

**Issue by ghost** [jostroOS/jostro#2]
i support icewm

**Comment by F-fengzi** [comment]
KEKW @buddyjojo

**Comment by ghost** [comment]
lo

**Comment by ghost** [comment]
ok send gf

**Comment by NoozAbooz** [comment]
i want jostro to ~die~ live

**Comment by ghost** [comment]
`i like yes`

**Comment by buddyjojo** [comment]
hopefully one day I'll get motivated to create 2.0

**Comment by ghost** [comment]
one day....

**Comment by NoozAbooz** [comment]
> hopefully one day I'll get motivated to create 2.0

just merge jostro with amogos 😎

**Comment by buddyjojo** [comment]
shut

**Comment by buddyjojo** [comment]
jostro is not supposed to be sus

**Comment by ghost** [comment]
[yes](https://jojoautoboysexy.com)

**Comment by NoozAbooz** [comment]
> [yes](https://jojoautoboysexy.com)

tf

**Comment by buddyjojo** [comment]
...

**Comment by F-fengzi** [comment]
> hopefully one day I'll get motivated to create 2.0

Today

**Comment by ghost** [comment]
https://search.brave.com/

**Comment by buddyjojo** [comment]
test

**Comment by ghost** [comment]
rip jostr

**Comment by buddyjojo** [comment]
hey I'm slowly working on it

**Comment by buddyjojo** [comment]
it's just that it's much more complex then i thought

**Comment by buddyjojo** [comment]
hopefully one day I'll get 2.0 released

**Comment by buddyjojo** [comment]
fuck i said that before

**Comment by NoozAbooz** [comment]
By the time Jostro 2 is released, amogos will be celebrating it's 50th release

**Comment by buddyjojo** [comment]
nah it'll probably die way before that

**Comment by ghost** [comment]
2.0

**Comment by buddyjojo** [comment]
no this issue will stay open until 2.0

**Comment by IAMACAR10** [comment]
jostro cannot die

**Comment by buddyjojo** [comment]
it will not die

**Comment by IAMACAR10** [comment]
then make a new release (take all the time you want of course)

**Comment by buddyjojo** [comment]
i mean I've been working on 2.0 for quite awhile now 
granted in short bursts but it's getting there

**Comment by IAMACAR10** [comment]
okay, looking forward to it :)
-sussy wussy impostor (tax fraud)

**Comment by ghost** [comment]
wen jostr 3.0 n 4.20

**Comment by IAMACAR10** [comment]
slow down, moon, you need to wait for version 69 first

**Comment by ghost** [comment]
jostro sex edition  !!!11!1!!11!!!!

**Comment by IAMACAR10** [comment]
background is just a porn video

Jojo autoroute if you don't make thus you will be sued and arrested

**Comment by DocdoZach** [comment]
> 

short bursts of cu-

**Comment by ghost** [comment]
brr jstr dd

**Comment by F-fengzi** [comment]
noooo
